-- Auto-generated config file
-- Generated by ConfigConvertTool
-- PrimitiveFormat: Csv
-- Mode: Array

return {
    {["Sign"] = "#", ["ID"] = "0", ["Character"] = "助手", ["PosAndOp"] = "center", ["Content"] = "恭喜！你已成功进入TalkTest2对话", ["NextID"] = "1", ["Func"] = ">PlaySound", ["Params"] = "success"},
    {["Sign"] = "#", ["ID"] = "1", ["Character"] = "助手", ["PosAndOp"] = "center&diff1", ["Content"] = "这是连续对话测试，证明对话系统可以无缝衔接", ["NextID"] = "2", ["Func"] = "", ["Params"] = ""},
    {["Sign"] = "#", ["ID"] = "2", ["Character"] = "测试NPC;助手", ["PosAndOp"] = "left;right", ["Content"] = "现在测试多角色连续对话", ["NextID"] = "3", ["Func"] = "", ["Params"] = ""},
    {["Sign"] = "#", ["ID"] = "3", ["Character"] = "测试NPC", ["PosAndOp"] = "left&diff2", ["Content"] = "我的表情也变化了！", ["NextID"] = "4", ["Func"] = "", ["Params"] = ""},
    {["Sign"] = "#", ["ID"] = "4", ["Character"] = "助手", ["PosAndOp"] = "right&diff1", ["Content"] = "这证明对话系统运行正常", ["NextID"] = "5", ["Func"] = "", ["Params"] = ""},
    {["Sign"] = "#", ["ID"] = "5", ["Character"] = "测试NPC;助手", ["PosAndOp"] = "left;hide", ["Content"] = "现在隐藏助手角色", ["NextID"] = "6", ["Func"] = "", ["Params"] = ""},
    {["Sign"] = "#", ["ID"] = "6", ["Character"] = "测试NPC", ["PosAndOp"] = "center", ["Content"] = "连续对话测试完成！", ["NextID"] = "END", ["Func"] = ">ShowSpecialEffect", ["Params"] = "complete"}
}
