-- Auto-generated config file
-- Generated by ConfigConvertTool
-- PrimitiveFormat: Csv
-- Mode: Array

return {
    {["Sign"] = "#", ["ID"] = "0", ["Character"] = "助手", ["PosAndOp"] = "center", ["Content"] = "你已成功进入TalkTest2对话（这依旧是热更的）", ["NextID"] = "1", ["Func"] = ">PlaySound", ["Params"] = "success"},
    {["Sign"] = "#", ["ID"] = "1", ["Character"] = "助手", ["PosAndOp"] = "center&diff1", ["Content"] = "这是连续对话测试，证明对话系统可以无缝衔接", ["NextID"] = "2", ["Func"] = "", ["Params"] = ""},
    {["Sign"] = "#", ["ID"] = "2", ["Character"] = "测试NPC;助手", ["PosAndOp"] = "left;right", ["Content"] = "这次来点选项", ["NextID"] = "3;4;5", ["Func"] = "", ["Params"] = ""},
    {["Sign"] = "%", ["ID"] = "3", ["Character"] = "", ["PosAndOp"] = "", ["Content"] = "都是结束对话，指向同一句", ["NextID"] = "6", ["Func"] = "", ["Params"] = ""},
    {["Sign"] = "%", ["ID"] = "4", ["Character"] = "", ["PosAndOp"] = "", ["Content"] = "都是结束对话，指向同一句", ["NextID"] = "6", ["Func"] = "", ["Params"] = ""},
    {["Sign"] = "%", ["ID"] = "5", ["Character"] = "", ["PosAndOp"] = "", ["Content"] = "都是结束对话，指向同一句", ["NextID"] = "6", ["Func"] = "", ["Params"] = ""},
    {["Sign"] = "#", ["ID"] = "6", ["Character"] = "测试NPC", ["PosAndOp"] = "center", ["Content"] = "热更的对话2测试完成！", ["NextID"] = "END", ["Func"] = ">ShowSpecialEffect", ["Params"] = "complete"}
}
