-- Auto-generated config file
-- Generated by ConfigConvertTool
-- PrimitiveFormat: Json
-- Mode: KeyValue

return {
    ["Root"] = {
        ["buff_1"] = {
            ["name"] = "buff1",
            ["time"] = 10,
            ["deplete"] = 100
        }
,
        ["buff_2"] = {
            ["name"] = "buff2",
            ["time"] = 15,
            ["deplete"] = 120
        }
,
        ["buff_3"] = {
            ["name"] = "buff3",
            ["time"] = 20,
            ["deplete"] = 150
        }

    }
}
