-- Auto-generated config file
-- Generated by ConfigConvertTool
-- PrimitiveFormat: Xml
-- Mode: KeyValue

return {
    ["GameSettings"] = {
        ["Graphics"] = {
            ["Resolution"] = "1920x1080",
            ["QualityLevel"] = "High",
            ["VSync"] = true,
            ["FPSLimit"] = 120
        }
,
        ["Audio"] = {
            ["MasterVolume"] = 0.85,
            ["MusicVolume"] = 0.7,
            ["SFXVolume"] = 0.9,
            ["VoiceVolume"] = 1
        }
,
        ["Controls"] = {
            ["KeyBinding_Attack"] = "Mouse0",
            ["KeyBinding_Skill1"] = "Q",
            ["KeyBinding_Skill2"] = "E",
            ["KeyBinding_Jump"] = "Space",
            ["MouseSensitivity"] = 1.2
        }
,
        ["Gameplay"] = {
            ["Difficulty"] = "Normal",
            ["AutoSave"] = true,
            ["AutoSaveInterval"] = 300,
            ["Language"] = "English"
        }

    }
}
