-- Auto-generated config file
-- Generated by ConfigConvertTool
-- PrimitiveFormat: Xml

return {
    ["Graphics"] = {["id"] = "Graphics", ["Resolution"] = "1920x1080", ["QualityLevel"] = "High", ["VSync"] = true, ["FPSLimit"] = 120, ["MasterVolume"] = nil, ["MusicVolume"] = nil, ["SFXVolume"] = nil, ["VoiceVolume"] = nil, ["KeyBinding_Attack"] = nil, ["KeyBinding_Skill1"] = nil, ["KeyBinding_Skill2"] = nil, ["KeyBinding_Jump"] = nil, ["MouseSensitivity"] = nil, ["Difficulty"] = nil, ["AutoSave"] = nil, ["AutoSaveInterval"] = nil, ["Language"] = nil},
    ["Audio"] = {["id"] = "Audio", ["Resolution"] = nil, ["QualityLevel"] = nil, ["VSync"] = nil, ["FPSLimit"] = nil, ["MasterVolume"] = 0.85, ["MusicVolume"] = 0.7, ["SFXVolume"] = 0.9, ["VoiceVolume"] = 1, ["KeyBinding_Attack"] = nil, ["KeyBinding_Skill1"] = nil, ["KeyBinding_Skill2"] = nil, ["KeyBinding_Jump"] = nil, ["MouseSensitivity"] = nil, ["Difficulty"] = nil, ["AutoSave"] = nil, ["AutoSaveInterval"] = nil, ["Language"] = nil},
    ["Controls"] = {["id"] = "Controls", ["Resolution"] = nil, ["QualityLevel"] = nil, ["VSync"] = nil, ["FPSLimit"] = nil, ["MasterVolume"] = nil, ["MusicVolume"] = nil, ["SFXVolume"] = nil, ["VoiceVolume"] = nil, ["KeyBinding_Attack"] = "Mouse0", ["KeyBinding_Skill1"] = "Q", ["KeyBinding_Skill2"] = "E", ["KeyBinding_Jump"] = "Space", ["MouseSensitivity"] = 1.2, ["Difficulty"] = nil, ["AutoSave"] = nil, ["AutoSaveInterval"] = nil, ["Language"] = nil},
    ["Gameplay"] = {["id"] = "Gameplay", ["Resolution"] = nil, ["QualityLevel"] = nil, ["VSync"] = nil, ["FPSLimit"] = nil, ["MasterVolume"] = nil, ["MusicVolume"] = nil, ["SFXVolume"] = nil, ["VoiceVolume"] = nil, ["KeyBinding_Attack"] = nil, ["KeyBinding_Skill1"] = nil, ["KeyBinding_Skill2"] = nil, ["KeyBinding_Jump"] = nil, ["MouseSensitivity"] = nil, ["Difficulty"] = "Normal", ["AutoSave"] = true, ["AutoSaveInterval"] = 300, ["Language"] = "English"}
}
